# make sure volumes exist before starting this
# mkdir -p {jenkins/volumes/var/jenkins_home,artifactory}
jenkins:
  image: jenkins/jenkins:2.84
  restart: always
  ports:
    - "80:8080"
    - "50000:50000"
  volumes:
    - ./jenkins/volumes/var/jenkins_home:/var/jenkins_home
artifactory:
  image: docker.bintray.io/jfrog/artifactory-oss:5.0.0
  restart: always
  ports:
    - "8081:8081"
  volumes:
    - "./artifactory:/var/opt/jfrog/artifactory"
